/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IKYCContractInterface extends ethers.utils.Interface {
  functions: {
    "isKyced(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "isKyced", values: [string]): string;

  decodeFunctionResult(functionFragment: "isKyced", data: BytesLike): Result;

  events: {
    "KYCED(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "KYCED"): EventFragment;
}

export type KYCEDEvent = TypedEvent<
  [string, boolean] & { subject: string; kyced: boolean }
>;

export class IKYCContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IKYCContractInterface;

  functions: {
    isKyced(addr: string, overrides?: CallOverrides): Promise<[boolean]>;
  };

  isKyced(addr: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    isKyced(addr: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "KYCED(address,bool)"(
      subject?: string | null,
      kyced?: null
    ): TypedEventFilter<[string, boolean], { subject: string; kyced: boolean }>;

    KYCED(
      subject?: string | null,
      kyced?: null
    ): TypedEventFilter<[string, boolean], { subject: string; kyced: boolean }>;
  };

  estimateGas: {
    isKyced(addr: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isKyced(
      addr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
