/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IKYCContract, IKYCContractInterface } from "../IKYCContract";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "addr",
        type: "address",
      },
    ],
    name: "isKyced",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        name: "subject",
        type: "address",
      },
      {
        indexed: false,
        name: "kyced",
        type: "bool",
      },
    ],
    name: "KYCED",
    type: "event",
  },
];

export class IKYCContract__factory {
  static readonly abi = _abi;
  static createInterface(): IKYCContractInterface {
    return new utils.Interface(_abi) as IKYCContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKYCContract {
    return new Contract(address, _abi, signerOrProvider) as IKYCContract;
  }
}
